# Generated by Django 5.0 on 2024-01-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_du_cours', to='users.educateur')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_du_rapport', to='users.utilisateur')),
                ('psy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psy_du_raport', to='users.psychologue')),
            ],
        ),
    ]
